### ISSUE TITLE
Couldn't use local video path

### ISSUE THREAD

**Issue by prakharjcis** [abhi3691/react-native-audio-remove#13]
I am trying to merge audio and video.
Its working well with http but how to use video from local storage??

**Comment by abhi3691** [comment]
I will check on local and get back to you

**Comment by abhi3691** [comment]
refer this github sample app code
https://github.com/abhi3691/videoprations.git 


add   add bellow permissions for andorid 13   <uses-permission android:name="android.permission.INTERNET" />
     <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
  <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
    android:maxSdkVersion="32" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />
